server:
  port: 8765
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: 192.168.230.101
      port: 8500
      discovery:
        register: false
feign:
  hystrix:
    enabled: true

consul-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule